// src/app/data.js
export const courses = Array.from({ length: 35 }, (_, i) => ({
  id: i + 1,
  title: `Course ${i + 1}`,
  category: `Category ${Math.floor(Math.random() * 3) + 1}`,
  enrollStudents: Math.floor(Math.random() * 100),
  price: (Math.random() * 100).toFixed(2),
  status: Math.random() < 0.5 ? "Active" : "Inactive",
  published: Math.random() < 0.5 ? "Yes" : "No",
}));


// src/app/data.js (or create a new data file)
export const students = [
  { id: 1, name: "Alice Smith", email: "alice@example.com", course: "Math 101" },
  { id: 2, name: "Bob Johnson", email: "bob@example.com", course: "Physics 201" },
  { id: 3, name: "Charlie Brown", email: "charlie@example.com", course: "History 301" },
  { id: 4, name: "David Lee", email: "david@example.com", course: "Computer Science 101" },
  { id: 5, name: "Eve Wilson", email: "eve@example.com", course: "English 201" },
  { id: 6, name: "Frank Miller", email: "frank@example.com", course: "Chemistry 301" },
  { id: 7, name: "Grace Davis", email: "grace@example.com", course: "Biology 101" },
  { id: 8, name: "Henry Garcia", email: "henry@example.com", course: "Art 201" },
  { id: 9, name: "Ivy Rodriguez", email: "ivy@example.com", course: "Music 301" },
  { id: 10, name: "Jack Martinez", email: "jack@example.com", course: "Physical Education 101" },
  { id: 11, name: "Karen Anderson", email: "karen@example.com", course: "Geography 201" },
  { id: 12, name: "Liam Thomas", email: "liam@example.com", course: "Economics 301" },
  { id: 13, name: "Mia Jackson", email: "mia@example.com", course: "Sociology 101" },
  { id: 14, name: "Noah White", email: "noah@example.com", course: "Psychology 201" },
  { id: 15, name: "Olivia Harris", email: "olivia@example.com", course: "Political Science 301" },
  // ... add more students as needed
];

export const certificates = [
  {
    id: 1,
    name: "Certificate of Completion",
    student: "Alice Smith",
    course: "Introduction to Web Development",
    issueDate: "2025-03-15",
    certificateNumber: "WEB101-AS-001",
    grade: "Pass",
  },
  {
    id: 2,
    name: "Certificate of Achievement",
    student: "Bob Johnson",
    course: "Advanced Data Science",
    issueDate: "2025-03-10",
    certificateNumber: "ADS201-BJ-002",
    grade: "Distinction",
  },
  {
    id: 3,
    name: "Course Completion",
    student: "Charlie Brown",
    course: "Fundamentals of Graphic Design",
    issueDate: "2025-03-01",
    certificateNumber: "GDF101-CB-003",
    grade: "Merit",
  },
  {
    id: 4,
    name: "Certificate of Participation",
    student: "Diana Lee",
    course: "Project Management Essentials",
    issueDate: "2025-02-20",
    certificateNumber: "PME101-DL-004",
    grade: "Completed",
  },
  {
    id: 5,
    name: "Certificate of Excellence",
    student: "Ethan Williams",
    course: "Mastering React",
    issueDate: "2025-02-10",
    certificateNumber: "REACT301-EW-005",
    grade: "Excellent",
  },
  {
    id: 6,
    name: "Certificate of Completion",
    student: "Fiona Garcia",
    course: "Python for Beginners",
    issueDate: "2025-01-25",
    certificateNumber: "PYT101-FG-006",
    grade: "Pass",
  },
  {
    id: 7,
    name: "Certificate of Achievement",
    student: "George Rodriguez",
    course: "Digital Marketing Strategy",
    issueDate: "2025-01-15",
    certificateNumber: "DMS201-GR-007",
    grade: "Distinction",
  },
  {
    id: 8,
    name: "Course Completion",
    student: "Hannah Martinez",
    course: "Mobile App Development with Flutter",
    issueDate: "2025-01-05",
    certificateNumber: "FLUTTER201-HM-008",
    grade: "Merit",
  },
  {
    id: 9,
    name: "Certificate of Participation",
    student: "Ian Thomas",
    course: "Business Analytics",
    issueDate: "2024-12-20",
    certificateNumber: "BA301-IT-009",
    grade: "Completed",
  },
  {
    id: 10,
    name: "Certificate of Excellence",
    student: "Julia Jackson",
    course: "Advanced JavaScript Concepts",
    issueDate: "2024-12-10",
    certificateNumber: "JS301-JJ-010",
    grade: "Excellent",
  },
  // Add more certificate data as needed
];

export const quizzes = [
  {
    id: 1,
    title: "Introduction to React Quiz",
    course: "Web Development Basics",
    dueDate: "2025-03-22",
    totalQuestions: 10,
    status: "Active",
  },
  {
    id: 2,
    title: "Data Structures and Algorithms Quiz 1",
    course: "Advanced Data Science",
    dueDate: "2025-03-25",
    totalQuestions: 15,
    status: "Pending",
  },
  {
    id: 3,
    title: "Typography Basics",
    course: "Fundamentals of Graphic Design",
    dueDate: "2025-03-18",
    totalQuestions: 8,
    status: "Completed",
  },
  {
    id: 4,
    title: "Agile Methodologies",
    course: "Project Management Essentials",
    dueDate: "2025-03-28",
    totalQuestions: 12,
    status: "Active",
  },
  {
    id: 5,
    title: "React Hooks Deep Dive",
    course: "Mastering React",
    dueDate: "2025-04-01",
    totalQuestions: 20,
    status: "Pending",
  },
  // Add more quiz data as needed
];

export const assignments = [
  {
    id: 1,
    title: "Build a Simple Portfolio Website",
    course: "Introduction to Web Development",
    dueDate: "2025-03-29",
    totalPoints: 100,
    status: "Active",
  },
  {
    id: 2,
    title: "Implement a Binary Search Tree",
    course: "Advanced Data Science",
    dueDate: "2025-04-02",
    totalPoints: 150,
    status: "Pending",
  },
  {
    id: 3,
    title: "Design a Logo for a Startup",
    course: "Fundamentals of Graphic Design",
    dueDate: "2025-03-22",
    totalPoints: 80,
    status: "Active",
  },
  {
    id: 4,
    title: "Create a Project Charter",
    course: "Project Management Essentials",
    dueDate: "2025-04-05",
    totalPoints: 120,
    status: "Pending",
  },
  {
    id: 5,
    title: "Develop a Custom Hook for Data Fetching",
    course: "Mastering React",
    dueDate: "2025-04-08",
    totalPoints: 180,
    status: "Active",
  },
]